version: '3'
services: 
    web:
        image: 'upvitor/debian-php:1.0'
        ports: 
        - "80:80"
        volumes: 
        - ./www/:/var/www/html
        container_name: debian
        links: 
            - db
    db:
        image: mysql:5.6
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3308:3306'
        volumes:
            - ../../db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: '4aw'
    admindb:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1